### ISSUE TITLE
Few performance issues & feature improvements

### ISSUE THREAD

**Issue by sanjay7178** [suryatejess/vit-course-reg-planner#3]
- I seen the app is deployed under stream hosting service , I appreciate the efforts you put it but I suggest to use any other python based frontend alternatives for FFCS Course planner (eg.. [Mesop](https://google.github.io/mesop/) ,gradio ..) or prefferable react , nextjs .. 
- Need a toggle for semester change so you no need to upload pdf's instead of uploading it , better to use a optimized python datastructure of the pdf data at the backend for every semester
- Add a disqus community comment element in the webpage footer

**Comment by suryatejess** [comment]
Thank you for your suggestions. We'll look into it.
Could you please elaborate on your 'toggle' thing. 
And coming to the discuss community feature, I have plans for it to add it by next semester when we make a website using react, nextjs etc

**Comment by sanjay7178** [comment]
> Thank you for your suggestions. We'll look into it. Could you please elaborate on your 'toggle' thing. And coming to the discuss community feature, I have plans for it to add it by next semester when we make a website using react, nextjs etc

Sorry I mean drop down element instead of toggle

**Comment by suryatejess** [comment]
You'll find it in our GUI app.
